"""Added init tables

Revision ID: 83fd1ff401dc
Revises: 
Create Date: 2024-02-25 03:52:44.590213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fd1ff401dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'RATHER_NOT_SAY', name='genderenum'), nullable=False),
    sa.Column('user_role', sa.Enum('ADMIN', 'CARETAKER', 'DOCTOR', 'PATIENT', name='combinedroleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('patient_caretaker_association_table',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('caretaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caretaker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('patient_doctor_association_table',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('patient_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('spo2_reading', sa.Float(), nullable=False),
    sa.Column('systolic_reading', sa.Integer(), nullable=False),
    sa.Column('diastolic_reading', sa.Integer(), nullable=False),
    sa.Column('temp_reading', sa.Float(), nullable=False),
    sa.Column('heartbeat_reading', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_additional_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'AB_POSITIOVE', 'AB_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'UNKNOWN', name='patientbloodgroupenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_additional_details_id'), 'user_additional_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_additional_details_id'), table_name='user_additional_details')
    op.drop_table('user_additional_details')
    op.drop_table('patient_histories')
    op.drop_table('patient_doctor_association_table')
    op.drop_table('patient_caretaker_association_table')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
